name: bobdow
favicon: null
layout_spectrum: 0.75347
typography_spectrum: 0.09051308920606971
title: "my name is bob dow, this stuff i'm working on "
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000002'
    - '#c3c1c4'
    - '#545255'
    - '#8b898c'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.3367222936358303
  rhythmicContrast: 0.5
purpose: []
