name: bobdow
favicon: null
layout_spectrum: 0.06484244368039072
typography_spectrum: 0.09051308920606971
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffd314'
    - '#e44391'
    - '#522c00'
    - '#c7790c'
  brandStrength: 0.73064538044855
  lightness: 0.4027375332079828
  saturation: 0.3367222936358303
  rhythmicContrast: 0.5
purpose: []
